#include "usd_prim_type.h"

void UsdPrimType::_bind_methods() {
	BIND_ENUM_CONSTANT(USD_PRIM_TYPE_XFORM);
	BIND_ENUM_CONSTANT(USD_PRIM_TYPE_MESH);
	BIND_ENUM_CONSTANT(USD_PRIM_TYPE_CAMERA);
	BIND_ENUM_CONSTANT(USD_PRIM_TYPE_MATERIAL);
	BIND_ENUM_CONSTANT(USD_PRIM_TYPE_SHADER);
	BIND_ENUM_CONSTANT(USD_PRIM_TYPE_SCOPE);
	BIND_ENUM_CONSTANT(USD_PRIM_TYPE_GEOM_SUBSET);
	BIND_ENUM_CONSTANT(USD_PRIM_TYPE_UNKNOWN);
}
